framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        exclude_patterns:
            - '*/assets/styles/_*.scss'
            - '*/assets/styles/**/_*.scss'
